### PR TITLE
Releasable verison

### PR DESCRIPTION
**Pull request by Omarley7**
We will be adressing the last 3 request on this PR.

> 1. iframe on the library page with the link taken from the env file. This iframe shall be common to all the tabs of that page.
> 2. env for test, dev, prod environments of react app
> 3. Align config, scripts of client/ with those of servers/lib. The config of client/ is to be adapted to servers/lib. The yarn commands are executed in a slight different way in servers/lib. If you can check these yarn commands with the script/ approach and select one, that would be great.

---
Please disregard the 23 commits before the last PR. We may have messed up a bit. At least "files changed" seems to play ball.

### CODE REVIEW

**Comment by prasadtalasila** [comment]
@Omarley7 please rebase to the latest commit on feature/distributed-demo branch and make the commits on that.

**Comment by Omarley7** [comment]
@prasadtalasila That should be rebased now! Thanks for the tip.

**Comment by prasadtalasila** [comment]
Tutorial on [different env for react app](https://www.opcito.com/blogs/managing-multiple-environment-configurations-in-react-app)

**Comment by Omarley7** [comment]
@prasadtalasila 

**iframe on every tab**
Should be fixed now. Currently using the same URL, but it does support dynamically changing enpoints based on tab with.

**Dynamic enviormen**
`yarn configapp` now reads from envirmentvariable set in terminal  by `export REACT_APP_ENV="dev | test | prod"`.

What ever variable set in `src/public/env.js`  during `yarn build` will be copied to the build folder and replace existing `env.js`.

Configurations are placed in the `config` folder as `dev.js`, `test.js` and `prod.js`. 

**Alignment of configuration**
We've met with @ravvnen and agreed that he'll conform to our configuration in regards to using scripts for testing, building and syntex etc.

**Comment by prasadtalasila** [comment]
@Omarley7 and @DaloonOfDoom 
> **Dynamic enviormen** `yarn configapp` now reads from envirmentvariable set in terminal by `export REACT_APP_ENV="dev | test | prod"`.
> 
> What ever variable set in `src/public/env.js` during `yarn build` will be copied to the build folder and replace existing `env.js`.
> 
> Configurations are placed in the `config` folder as `dev.js`, `test.js` and `prod.js`.

The objective is to configure after build is done. We want to zip the contents of build directory, give it to users who can modify some config files within build/ and they are good to go.

**Comment by prasadtalasila** [comment]
BTW, we still need different env setup using `yarn configapp`.
@DaloonOfDoom , isn't there a React compliant way of doing `yarn configapp`?

**Comment by Omarley7** [comment]
@prasadtalasila
> The objective is to configure after build is done. We want to zip the contents of build directory, give it to users who can modify some config files within build/ and they are good to go.

`yarn configapp` will also update the build folder (if present) with the new env.js. So no need to rebuild, which makes zipping and shipping possible. Users would just need to modify `/build/env.js`.

**Comment by prasadtalasila** [comment]
Some issues:
1. The iframe isn't responsive in the vertical direction on firefox browser. This is true on all the pages. Is there a way to write a playwright test to check for this responsiveness? If a proper test is written, it would fail only on the firefox browser. Then the code can be fixed and the test should be successful.
2. There is `env.d.js` file in `config/.` Is this used?
3. We haven't talked about this, but there is an issue with the unit tests. They are skeletal at the moment and don't test anything. Can you put unit tests there?

**Comment by prasadtalasila** [comment]
Please put one CLIENT.md containing instructions in `docs/` with instructions on running the client website by users. We can package and publish the client package as soon as we are ready with authentication.

**Comment by prasadtalasila** [comment]
We need to merge this PR so that other PRs can move forward. @Omarley7 can you please list the improvements already done so that we can decide on merging this PR and moving the remaining work to next PR?

**Comment by Omarley7** [comment]
@prasadtalasila here's the status so far:

## Implemented
- Fixed iframe issue on firefox
- Test shells are actually running without crashing.
- `window.env.`  `REACT_APP_ENVIRONMENT` || `REACT_APP_URL_LIB` || `REACT_APP_URL_DT` || `REACT_APP_URL_WORKBENCH` can be used without assertion.
- `yarn configapp dev||prod||test` will use associated config file in the config dir and update both `src/public` as well as build.
- Refactored for Digital Twin and Libary to be in seperate file, making the components more dynamic. (Duplication issue)
-  
----
## Not Implemented
- No actual tests yet
- Code smells and 
- Readme file

**Pull request merged**
