### PR TITLE
Authentication

### PR DESCRIPTION
**Pull request by KarstenMalle**
@prasadtalasila 
The rebase was done in accordance with feature/distributed-demo, and I see that authentication branch is 1 commit ahead and 1 commit behind.

### CODE REVIEW

**Comment by prasadtalasila** [comment]
@KarstenMalle I changed the upstream branch to feature/distributed-demo to remove merge conflicts. There are some old commits here that should be in the PR. Please correct this problem.

**Comment by prasadtalasila** [comment]
Please see the commit graph below.

image

artin13/authentication branch is not rebased to feature/distributed-demo branch.

**Comment by Artin13** [comment]
> Please see the commit graph below.
> 
> image
> 
> artin13/authentication branch is not rebased to feature/distributed-demo branch.

We get this 
image

**Comment by prasadtalasila** [comment]
The `into-cps-association/dtaas/feature/distributed-demo` was merged into `artin13/authentication`. A rebase is required here. Instead a merge was done.

**Comment by KarstenMalle** [comment]
> The `into-cps-association/dtaas/feature/distributed-demo` was merged into `artin13/authentication`. A rebase is required here. Instead a merge was done.

Aha okay, we will get this fixed. Sorry for the problem.

**Comment by prasadtalasila** [comment]
@KarstenMalle , I have also rebased the authentication branch.

**Comment by prasadtalasila** [comment]
The PR #71 does the same thing and it was merged.

**Pull request closed without merging**
