### PR TITLE
Fixes the stalling dev container

### PR DESCRIPTION
**Pull request by atomicgamedeveloper**
# Pull Request Template

## Title

Fixes the stalling dev container

## Type of Change

- [ ] New feature
- [X] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Security patch
- [ ] UI/UX improvement

## Description
I exchanged the `ghcr.io/devcontainers-contrib/features/mkdocs:2` which derives from a currently inactive repo to the corresponding layer from the active fork of it, https://github.com/devcontainers-extra/features?tab=readme-ov-file.

## Testing

I successfully have built the dev container. This was infeasible before. 

## Impact
- One of the layers is now maintained in a different repository.
- The other layers may eventually stop working unless the original repository reactivates.

## Additional Information

Issue discussing this: https://github.com/devcontainers-contrib/features/issues/623

## Checklist

- [X] My code adheres to the coding and style guidelines of the project.
- [X] I have added tests for all the new code and any changes made to
      existing code.
- [X] I have made corresponding changes to the documentation.

### CODE REVIEW

**Comment by prasadtalasila** [comment]
> The other layers may eventually stop working unless the original repository reactivates.

@atomicgamedeveloper what does this mean? I thought the layers are independent!

**Comment by prasadtalasila** [comment]
Please upgrade the node to v22.x and yarn to the latest version. Please also upgrade the dependencies and layers to their latest versions.

**Comment by atomicgamedeveloper** [comment]
> > The other layers may eventually stop working unless the original repository reactivates.
> 
> @atomicgamedeveloper what does this mean? I thought the layers are independent!

The other feature layers come from the same inactive repository, so they may face similar issues down the line when we rebuild. A simple solution is just to replace all the sources to the active one.

> Please upgrade the node to v22.x and yarn to the latest version. Please also upgrade the dependencies and layers to their latest versions.

Will do now.

**Comment by prasadtalasila** [comment]
There is a new PR #1063 that is equivalent to this PR.

**Pull request closed without merging**
