### PR TITLE
#68 - Github Actions success - Codecov failing silently

### PR DESCRIPTION
**Pull request by ravvnen**

### CODE REVIEW

**Comment by prasadtalasila** [comment]
@ravvnen , please rebase to the latest commit on feature/disyributed-demo branch. If you can squash the commits to a manageable number, say < 5, that would aid a great deal in speedy processing of your PR. The cross-checking of comments, commits and new problems is getting complicated because of too many commits.

**Comment by ravvnen** [comment]
@prasadtalasila - wouldnt it be easier if i just made a new branch based off the upstream/feature, and then made the codecov change there

**Comment by ravvnen** [comment]
@prasadtalasila - i hope its fine that i look at this one of the next days, as my focus right now is on finishing up the report

**Comment by prasadtalasila** [comment]
> @prasadtalasila - wouldnt it be easier if i just made a new branch based off the upstream/feature, and then made the codecov change there

yes it would be

**Comment by prasadtalasila** [comment]
@ravvnen will make a new PR.

**Comment by ravvnen** [comment]
@prasadtalasila - Super, thanks! Let me know if you are bored, i have some tedious rapport tasks that you could help with 😉
Can't wait to get out and enjoy the sun 😆

**Pull request closed without merging**
