### PR TITLE
Fixes for worker16 auth.setup.ts

### PR DESCRIPTION
**Pull request by KarstenMalle**

### CODE REVIEW

**Comment by KarstenMalle** [comment]
@prasadtalasila remember if you wanna test it out to update the `test/.env` file:

```
REACT_APP_TEST_USERNAME=testUsername
REACT_APP_TEST_PASSWORD=testPassword
REACT_APP_BASIC_AUTH_USERNAME=serverUsername
REACT_APP_BASIC_AUTH_PASSWORD=serverPassword
REACT_APP_URL=appURL
```

**Comment by prasadtalasila** [comment]
@Omarley7 , you mentioned about potential changes to [client/src/route/auth/Signin.tsx](https://github.com/Artin13/DTaaS/pull/1/files#diff-bfafc6ca9a7f8d0a1494cc5a6d14388c5a8cf9e5593549295565819ffc07b6f1). Do they need to be done before this PR? or Can they be done after?

**Comment by prasadtalasila** [comment]
@KarstenMalle , I am not able to replicate the result. The E2E tests still fail with or without http authentication.

In addition, two changes are required in this PR:

1. Resolve merge conflicts
2. Update test/README.md

**Comment by prasadtalasila** [comment]
> @prasadtalasila remember if you wanna test it out to update the `test/.env` file:
> 
> ```
> REACT_APP_TEST_USERNAME=testUsername
> REACT_APP_TEST_PASSWORD=testPassword
> REACT_APP_BASIC_AUTH_USERNAME=serverUsername
> REACT_APP_BASIC_AUTH_PASSWORD=serverPassword
> REACT_APP_URL=appURL

The `REACT_APP_URL` is already in `config/test.js`. Perhaps it can be used from there?

**Comment by KarstenMalle** [comment]
> > @prasadtalasila remember if you wanna test it out to update the `test/.env` file:
> > ```
> > REACT_APP_TEST_USERNAME=testUsername
> > REACT_APP_TEST_PASSWORD=testPassword
> > REACT_APP_BASIC_AUTH_USERNAME=serverUsername
> > REACT_APP_BASIC_AUTH_PASSWORD=serverPassword
> > REACT_APP_URL=appURL
> > ```
> 
> The `REACT_APP_URL` is already in `config/test.js`. Perhaps it can be used from there?

I tried that, it dindt work. I would just get import errors.

**Comment by KarstenMalle** [comment]
> @Omarley7 , you mentioned about potential changes to [client/src/route/auth/Signin.tsx](https://github.com/Artin13/DTaaS/pull/1/files#diff-bfafc6ca9a7f8d0a1494cc5a6d14388c5a8cf9e5593549295565819ffc07b6f1). Do they need to be done before this PR? or Can they be done after?

Are the changes not in `Library.tsx`? If so then those can be done afterwards.

**Comment by Omarley7** [comment]
> @Omarley7 , you mentioned about potential changes to [client/src/route/auth/Signin.tsx](https://github.com/Artin13/DTaaS/pull/1/files#diff-bfafc6ca9a7f8d0a1494cc5a6d14388c5a8cf9e5593549295565819ffc07b6f1). Do they need to be done before this PR? or Can they be done after?

They can be done after, since you are using the redux dispatch, it won't break as I initially thought ✌️

**Comment by KarstenMalle** [comment]
> **Please do not post password / secrets on the github**. You just added half a day of work for me to recreate the Integration Server.

Oh im sorry, where did I do this?

**Comment by KarstenMalle** [comment]
Ah damn I see it now, im sorry.

**Comment by prasadtalasila** [comment]
> Ah damn I see it now, im sorry.

It is alright. I have taken down the integration server and will rebuild it later today.  If the server setup is complete today, I will check this PR tonight. Otherwise, it will have to be tomorrow morning. I will comment here as soon as the check is done. Thanks for waiting.

**Comment by prasadtalasila** [comment]
@KarstenMalle , you updated the playwright code to consider HTTP authentication. Can you tell me test setup with which the test actually passed for you?

**Comment by prasadtalasila** [comment]
A new PR will be opened without HTTP authentication.

**Pull request closed without merging**
