### PR TITLE
Validates client config new

### LINKED ISSUE #658: Validate react website configuration
The react website [config spec](https://github.com/INTO-CPS-Association/DTaaS/blob/feature/distributed-demo/client/env.d.ts) is out of date with respect to the latest version of [config](https://github.com/INTO-CPS-Association/DTaaS/tree/feature/distributed-demo/client/config). The config spec needs to be updated.

In addition a json validator function needs to be written using [zod](https://zod.dev/). The new function can be placed in [envUtils](https://github.com/INTO-CPS-Association/DTaaS/blob/feature/distributed-demo/client/src/util/envUtil.ts) and invoked before using any variables from `env.js`.

### PR DESCRIPTION
**Pull request by atomicgamedeveloper**
Copied from previous PR https://github.com/INTO-CPS-Association/DTaaS/pull/1083:
## Title

Validates client config.

Fixes #658 

## Type of Change

- [X] New feature
- [X] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Security patch
- [ ] UI/UX improvement

## Description

This PR will provide a route to validate the client config file. A comprehensive, manual one for developers, and another one that automatically redirects users in case their config is incorrectly setup or URLs are unreachable.
It will also update the client dependencies. Related to issue https://github.com/INTO-CPS-Association/DTaaS/issues/658.

## Testing

Manual testing for now.

## Impact

- Zod dependency.
- Once complete, the website access flow will be different if your config is wrong.
- LayoutPublic is parameterized with a possible Breakpoint instead of always being 'xs'.
- Additional route of '/verify'

## Additional Information

None.

## Checklist

- [X] My code adheres to the coding and style guidelines of the project.
- [ ] I have added tests for all the new code and any changes made to
      existing code.
- [ ] I have made corresponding changes to the documentation.

### CODE REVIEW

**Comment by prasadtalasila** [comment]
@atomicgamedeveloper please add the changes on your `fearure/distributed-demo` and make a PR from there. Thanks.

**Comment by atomicgamedeveloper** [comment]
> @atomicgamedeveloper please add the changes on your `fearure/distributed-demo` and make a PR from there. Thanks.

I don't follow, sorry. Could you please elaborate?

**Comment by prasadtalasila** [comment]
@atomicgamedeveloper please follow these steps:

1. Force push your `658-validate-client-config-2` to your `feature/distributed-demo` branch
2. Open a new PR from your `feature/distributed-demo` branch to `feature/distributed-demo` branch of https://github.com/INTO-CPS-Association/DTaaS

Is it clear now?

**Comment by atomicgamedeveloper** [comment]
> @atomicgamedeveloper please add the changes on your `fearure/distributed-demo` and make a PR from there. Thanks.

I am not sure that I understand.

> @atomicgamedeveloper please follow these steps:
> 
>     1. Force push your `658-validate-client-config-2` to your `feature/distributed-demo` branch
> 
>     2. Open a new PR from your `feature/distributed-demo` branch to `feature/distributed-demo` branch of https://github.com/INTO-CPS-Association/DTaaS
> 
> 
> Is it clear now?

Yes, thank you.

**Pull request closed without merging**
