### PR TITLE
Finsihed JSX to TSX

### PR DESCRIPTION
**Pull request by Omarley7**
- Fixed the tests
- Added footer
- Removed babel.cjs
- Made `yarn test` close server after running
- Added `yarn dev` for live development

### CODE REVIEW

**Comment by Omarley7** [comment]
Will you take a look when you have a chance ? @prasadtalasila

**Comment by Omarley7** [comment]
@prasadtalasila This PR should be ready for review. 

Please note that the config/dev.js is not converted yet. Seemed to be okay to leave after looking at the config.bash. (I guess the .ts file needed to be converted to .js before being sent to the build folder)

**Comment by prasadtalasila** [comment]
* remove babel.config.cjs ?? (need to be checked)
* update browser list for playwright
* linting warnings?
* response height for iframes to make the div grow for fitting the iframe content
* react compliant env variables to frontend
* refactor the tab code in _library_ and _digital twin_ pages

**Comment by SyntaxXeror** [comment]
@prasadtalasila You say that we need to remove babel.config.cjs, but as we can figure out, we need babel to test with jest. Babel should work with TypeScript, and is good for transpiling if it is needed. Do you have a comment to this? Or else we'll leave babel.config.cjs.

**Comment by Omarley7** [comment]
@prasadtalasila This PR should be done and ready to go. Please let us know if there's anything we need to update.

**Comment by prasadtalasila** [comment]
> @prasadtalasila You say that we need to remove babel.config.cjs, but as we can figure out, we need babel to test with jest. Babel should work with TypeScript, and is good for transpiling if it is needed. Do you have a comment to this? Or else we'll leave babel.config.cjs.

@SyntaxXeror , please keep it.

**Comment by Omarley7** [comment]
@prasadtalasila I've fixed the .env error. `yarn configapp` is no longer needed, since the variable is being read directly during runtime from .ENV. 
Do you still wish to keep the script?

**Comment by prasadtalasila** [comment]
> @prasadtalasila I've fixed the .env error. `yarn configapp` is no longer needed, since the variable is being read directly during runtime from .ENV. Do you still wish to keep the script?

we need one env for different environments - production, development and testing. Is there a clean way to have different configs in a react app? If not, we can use the config script. For now, please use the script. Let's merge this PR and consider refactoring the _scripts/_ later.

**Comment by Omarley7** [comment]
@prasadtalasila gotcha, I've addressed the issues you mentioned in the previous comment. 

> * Failing integration tests
Button didn't hide after first click

> * workbench icon and the corresponding page are missing.
Added this page with generic iframe for now.

> * There is also a env.tmp file 
Removed this file and updatede the correct one.

>   The iframe remains blank.
Was an error with the .ENV - missed REACT_APP_ prefix

> * If it's easy to fit Grid to fill all the page, that may be visually nice.
Done.

@DaloonOfDoom Maybe you can look into the dynamic config setup?

**Comment by prasadtalasila** [comment]
@Omarley7 thanks for the updates.

**Failing Tests:**
```
  4 failed
    [chromium] › Auth.test.ts:7:3 › Tests on Authentication Flow › Homepage has correct title and signin link 
    [chromium] › Auth.test.ts:32:3 › Tests on Authentication Flow › Account Button Contents and Links 
    [chromium] › Menu.test.ts:72:3 › Header Contents and Navigation Links › Navigation Links on the Scenario Analysis page 
    [firefox] › Auth.test.ts:32:3 › Tests on Authentication Flow › Account Button Contents and Links 
```
The rest seems alright. Please fix this so that we can merge the code and say a small cheers.

**Comment by Omarley7** [comment]
@prasadtalasila that is very strange, I get pass on all 14 tests. Just tried again with these commands.

```bash
yarn clean
yarn install
yarn build
yarn configapp
yarn test
```
Is there something I'm missing? I notice it's 3 on chromium and 1 on firefox, which peaks my intrest. Is it possible you can send me the playwright report?

**Pull request merged**
