### PR TITLE
E2E testing fixed

### PR DESCRIPTION
**Pull request by KarstenMalle**
@prasadtalasila 
I've made a testing env file to ensure the environment supports the e2e tests. 
auth.setup.ts is now used to handle the authentication process, it requires valid GitLab credentials for testing. 
Chromium/chrome is not supported by GitLab for E2E Playwright tests, so current config is only using Firefox.
Noteworthy files for configuration of E2E tests are:
| Name | Header |
|--------|--------|
| test.js | Testing environment |
| playwright.config.ts | Config file for playwright, ensures auth.setup.ts is setup prior to tests, specifies to use Firefox browser |
| auth.setup.ts | Handles OIDC OAuth GitLab authentication process, requires valid GitLab user credentials |  

As I don't want to expose user password E2E is not properly setup, to make it work just provide the password (same as user1) in: 
```
await page.fill('#user_password', ''); // Insert valid GitLab testing password.
```

### CODE REVIEW

**Comment by KarstenMalle** [comment]
> @KarstenMalle , I have made a mess of the commit message and have to force update the feature/distributed-demo to fix this problem. Please rebase again. Sorry about the mixup.

No worries, it's rebased now :)

**Comment by prasadtalasila** [comment]
@KarstenMalle , can you please squash all your commits to one just to help me see the changes done after the rebase? If you don't mind the two-step process, we can change the base branch to authentication and look at the new changes done in this PR. After everything is ok, we can merge code into authentication and from authentication to feature/distributed-demo. This will help me quickly check through the PR.

If you would rather have one PR, then please squash all the changes to one commit. Thanks.

**Comment by KarstenMalle** [comment]
> @KarstenMalle , can you please squash all your commits to one just to help me see the changes done after the rebase? If you don't mind the two-step process, we can change the base branch to authentication and look at the new changes done in this PR. After everything is ok, we can merge code into authentication and from authentication to feature/distributed-demo. This will help me quickly check through the PR.
> 
> If you would rather have one PR, then please squash all the changes to one commit. Thanks.

Okay I will then close this PR and open a new one for the authentication branch

**Comment by KarstenMalle** [comment]
@prasadtalasila Could you please update the authentication branch to be up to date with the feature branch

**Pull request closed without merging**
