### PR TITLE
  Gitlab authentication (#66)

### PR DESCRIPTION
**Pull request by prasadtalasila**
- Adds gitlab oauth authentication for users. The oauth works for both local instance of gitlab and gitlab.com.
  - Update client.yml to run only unit and integration tests.

### CODE REVIEW

**Comment by prasadtalasila** [comment]
@KarstenMalle , there are a couple of folders in `servers/lib/test/data` that are redundant. I have removed them, rebased and squashed the commits into the PR branch.

After checking on the integration server and my computer, here are the results:


### react website authentication:

| Host | gitlab authenticator | result |
|:---|:---|:---|
| localhost | worker15 | ok |
| localhost | gitlab | ok |
| worker16 | worker15 | ok |
| worker16 | gitlab | ok |


### E2E test:

| Host | gitlab authenticator | result |
|:---|:---|:---|
| localhost | worker15 | ok |
| localhost | gitlab | ok |
| worker16 | worker15 | **fail** |
| worker16 | gitlab | **fail** |

The problem has only been observed on the integration server (worker16.lab.cps.digit.au.dk).

I've tried three configurations for `config/test.js`:

```
window.env = {
  REACT_APP_ENVIRONMENT: 'dev',
  REACT_APP_URL: 'http://localhost:4000/',
  REACT_APP_URL_BASENAME: '',
  REACT_APP_URL_DTLINK: '/lab',
  REACT_APP_URL_LIBLINK: '',
  REACT_APP_WORKBENCHLINK_TERMINAL: '/terminals/main',
  REACT_APP_WORKBENCHLINK_VNCDESKTOP: '/tools/vnc/?password=vncpassword',
  REACT_APP_WORKBENCHLINK_VSCODE: '/tools/vscode/',
  REACT_APP_WORKBENCHLINK_JUPYTERLAB: '/lab',
  REACT_APP_WORKBENCHLINK_JUPYTERNOTEBOOK: '',

  REACT_APP_CLIENT_ID: '934b98f03f1b6f743832b2840bf7cccaed93c3bfe579093dd0942a433691ccc0',
  REACT_APP_AUTH_AUTHORITY: 'https://worker15.lab.cps.digit.au.dk/',
  REACT_APP_REDIRECT_URI: 'http://localhost:4000/Library',
  REACT_APP_LOGOUT_REDIRECT_URI: 'http://localhost:4000/',
  REACT_APP_GITLAB_SCOPES: 'openid profile read_user read_repository api',
};
```

```
window.env = {
  REACT_APP_ENVIRONMENT: 'dev',
  REACT_APP_URL: 'https://worker16.lab.cps.digit.au.dk/',
  REACT_APP_URL_BASENAME: '',
  REACT_APP_URL_DTLINK: '/lab',
  REACT_APP_URL_LIBLINK: '',
  REACT_APP_WORKBENCHLINK_TERMINAL: '/terminals/main',
  REACT_APP_WORKBENCHLINK_VNCDESKTOP: '/tools/vnc/?password=vncpassword',
  REACT_APP_WORKBENCHLINK_VSCODE: '/tools/vscode/',
  REACT_APP_WORKBENCHLINK_JUPYTERLAB: '/lab',
  REACT_APP_WORKBENCHLINK_JUPYTERNOTEBOOK: '',

  REACT_APP_CLIENT_ID: '934b98f03f1b6f743832b2840bf7cccaed93c3bfe579093dd0942a433691ccc0',
  REACT_APP_AUTH_AUTHORITY: 'https://worker15.lab.cps.digit.au.dk/',
  REACT_APP_REDIRECT_URI: 'https://worker16.lab.cps.digit.au.dk/Library',
  REACT_APP_LOGOUT_REDIRECT_URI: 'https://worker16.lab.cps.digit.au.dk/',
  REACT_APP_GITLAB_SCOPES: 'openid profile read_user read_repository api',
};
```

```
window.env = {
  REACT_APP_ENVIRONMENT: 'dev',
  REACT_APP_URL: 'https://worker16.lab.cps.digit.au.dk/',
  REACT_APP_URL_BASENAME: '',
  REACT_APP_URL_DTLINK: '/lab',
  REACT_APP_URL_LIBLINK: '',
  REACT_APP_WORKBENCHLINK_TERMINAL: '/terminals/main',
  REACT_APP_WORKBENCHLINK_VNCDESKTOP: '/tools/vnc/?password=vncpassword',
  REACT_APP_WORKBENCHLINK_VSCODE: '/tools/vscode/',
  REACT_APP_WORKBENCHLINK_JUPYTERLAB: '/lab',
  REACT_APP_WORKBENCHLINK_JUPYTERNOTEBOOK: '',

  REACT_APP_CLIENT_ID: '1be55736756190b3ace4c2c4fb19bde386d1dcc748d20b47ea8cfb5935b8446c',
  REACT_APP_AUTH_AUTHORITY: 'https://gitlab.com/',
  REACT_APP_REDIRECT_URI: 'https://worker16.lab.cps.digit.au.dk/Library',
  REACT_APP_LOGOUT_REDIRECT_URI: 'https://worker16.lab.cps.digit.au.dk/',
  REACT_APP_GITLAB_SCOPES: 'openid profile read_user read_repository api',
};
```

The test/.env was changed accordingly.

Do you have any clue?

**Comment by prasadtalasila** [comment]
The [authentication](https://github.com/INTO-CPS-Association/DTaaS/tree/authentication) branch works fine and the files are the same as the `prasadtalasila/dtaas-public/feature/distributed-demo` branch. So it bugs me.

**Comment by KarstenMalle** [comment]
Hmm that is strange. So the authentication branch does not fail here? : 
image

Seems like I can't currently access worker16 server (I think its down?) but i'll try again tomorrow and figure this out.

I assume the `REACT_APP_TEST_USERNAME` and `REACT_APP_TEST_PASSWORD` are set correctly in test/.env for the corresponding `REACT_APP_CLIENT_ID`.

It might be due to the time it takes between redirects, however I doubt this is the reason.

I ran into some issues earlier as you know with the way worker15 handles cookies, perhaps this is the same issue for worker16, maybe some cookie configuration is required. 

I can't say for sure right now, but i'll look into this once I can connect to the server :)

**Comment by KarstenMalle** [comment]
I still can't access worker16 server.

**Comment by prasadtalasila** [comment]
> I still can't access worker16 server.

I am working on it right now. Are you on VPN?

**Comment by KarstenMalle** [comment]
> Yes I am on AU VPN

**Comment by prasadtalasila** [comment]
> > > I still can't access worker16 server.
> > 
> > 
> > I am working on it right now. Are you on VPN?
> 
> Yes I am on AU VPN

Let us have a quick chat on Teams. I have sent the link to your email.

**Comment by KarstenMalle** [comment]
Would the usual user of DTaaS use our authentication layer and then this is not a issue or am I wrong?

**Comment by prasadtalasila** [comment]
> @prasadtalasila Would the usual user of DTaaS have a username and password for their application?

No. The HTTP authentication was put in place as a temporary substitute for Gitlab OAuth. It would go away as soon as the Gitlab Oauth is running successfully.
Thank you for the debugging. I will now remove the basic authentication and check the tests again on the integration server.
Can you also open a PR onto the authentication branch so that I can look at the changes you made to make the test work?

**Comment by KarstenMalle** [comment]
> > @prasadtalasila Would the usual user of DTaaS have a username and password for their application?
> 
> No. The HTTP authentication was put in place as a temporary substitute for Gitlab OAuth. It would go away as soon as the Gitlab Oauth is running successfully. Thank you for the debugging. I will now remove the basic authentication and check the tests again on the integration server. Can you also open a PR onto the authentication branch so that I can look at the changes you made to make the test work?

Yes, the current changes only fix the authentication part of the e2e test (`auth.setup.ts`), that means, the `Auth.test.ts` and `Menu.test.ts` might not working correctly as they might be asked for `worker16` username and password at some points which the tests are not set up for handling. I could fix this but it would take some time and effort.

**Comment by prasadtalasila** [comment]
Let us not get there. Let the code be tested with out HTTP authentication on the integration server. If the tests pass in that scenario, let us merge it.

**Comment by KarstenMalle** [comment]
> Let us not get there. Let the code be tested with out HTTP authentication on the integration server. If the tests pass in that scenario, let us merge it.

Okay great, I have made the PR. Let me know if there is anything :)

**Comment by prasadtalasila** [comment]
PR #81 was an update on this PR.

**Pull request closed without merging**
