### PR TITLE
OIDC Auth 

### PR DESCRIPTION
**Pull request by Artin13**

### CODE REVIEW

**Comment by prasadtalasila** [comment]
please resolve the test failure and duplication issues.

**Comment by prasadtalasila** [comment]
@Artin13 and @KarstenMalle, is there any working pending from your side on this PR or are you just waiting for my approval of this PR?

**Comment by KarstenMalle** [comment]
> @Artin13 and @KarstenMalle, is there any working pending from your side on this PR or are you just waiting for my approval of this PR?

Yeah we just need to get e2e tests working with nock now. We will try to have this done by today.

**Comment by KarstenMalle** [comment]
We still can't properly mock the authentication process. The issue is with the redirect call to the GitLab sign in page, it detects that playwright is trying to connect and blocks it. Also trying to mock the Fetch/XHR requests doesn't seem to work or then we are just doing it wrong. We've been working on this the last 2 days and haven't really made progress. The documentation for mocking OIDC authentication is minimal. I will be working on this for the rest of today but we also have other projects that require our attention. We can talk about all of this tomorrow :)

**Comment by prasadtalasila** [comment]
Please fix the conflicts and codeclimate issues.

**Comment by prasadtalasila** [comment]
PR #66 includes the changes suggested here.

**Pull request closed without merging**
