### PR TITLE
Fixes the stalling container

### PR DESCRIPTION
**Pull request by atomicgamedeveloper**
# Pull Request Template

## Title

804 fixes stalling container of this issue https://github.com/INTO-CPS-Association/DTaaS/issues/804

## Type of Change

- [ ] New feature
- [X] Bug fix
- [X] Documentation update
- [ ] Refactoring
- [ ] Security patch
- [ ] UI/UX improvement

## Description

I have migrated the layers of the container to ones in a repository that is more active (has more than 1 developer) and fixed the 
tests that were broken by the performance of the dev container. This, simply by incrementing their respective timeouts and adding a moduleNameMapper field to `DTaaS/servers/lib/test/jest-e2e.json`. I also updated some documentation regarding the need to install pm2 when running tests on the dev container.

## Testing
All tests have been run in the libms subfolder and most tests have been run in the runner folder.

## Impact

The added timeouts, especially to the no-cov test adds a flat 40 seconds to the testing time.

## Additional Information
None.

## Checklist

- [X] My code adheres to the coding and style guidelines of the project.
- [ ] I have added tests for all the new code and any changes made to
      existing code.
- [X] I have made corresponding changes to the documentation.

### CODE REVIEW

**Comment by prasadtalasila** [comment]
@atomicgamedeveloper The error seen inside the devcontainer:

```bash
node ➜ /workspaces/DTaaS/servers/lib (enok-new-devcontainer) $ yarn test:int
yarn run v1.22.22
$ npx cross-env NODE_OPTIONS=--experimental-vm-modules LOCAL_PATH=test/data jest ../test/integration --coverage
(node:5423) ExperimentalWarning: VM Modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
 FAIL  test/integration/files.service.integration.spec.ts (5.568 s)
  Integration tests for FilesResolver
    when MODE is local
      ✕ should be defined (19 ms)
      listDirectory
        ✕ should list files (4 ms)
      readFile
        ✕ should read file (3 ms)

  ● Integration tests for FilesResolver › when MODE is local › should be defined

    Invalid MODE: unknown

      13 |
      14 |     if (service == undefined) {
    > 15 |       throw new Error(`Invalid MODE: ${mode}`);
         |             ^
      16 |     }
      17 |     return service;
      18 |   }

      at Function.create (src/files/files-service.factory.ts:15:13)
      at InstanceWrapper.useFactory [as metatype] (test/integration/files.service.integration.spec.ts:34:40)
      at TestingInjector.instantiateClass (node_modules/@nestjs/core/injector/injector.js:368:55)
      at callback (node_modules/@nestjs/core/injector/injector.js:65:45)
      at async TestingInjector.resolveConstructorParams (node_modules/@nestjs/core/injector/injector.js:144:24)
      at async TestingInjector.loadInstance (node_modules/@nestjs/core/injector/injector.js:70:13)
      at async TestingInjector.loadProvider (node_modules/@nestjs/core/injector/injector.js:97:9)
      at async /workspaces/DTaaS/servers/lib/node_modules/@nestjs/core/injector/instance-loader.js:56:13
          at async Promise.all (index 4)
      at async TestingInstanceLoader.createInstancesOfProviders (node_modules/@nestjs/core/injector/instance-loader.js:55:9)
      at async /workspaces/DTaaS/servers/lib/node_modules/@nestjs/core/injector/instance-loader.js:40:13
          at async Promise.all (index 1)
      at async TestingInstanceLoader.createInstances (node_modules/@nestjs/core/injector/instance-loader.js:39:9)
      at async TestingInstanceLoader.createInstancesOfDependencies (node_modules/@nestjs/core/injector/instance-loader.js:22:13)
      at async TestingInstanceLoader.createInstancesOfDependencies (node_modules/@nestjs/testing/testing-instance-loader.js:9:9)
      at async TestingModuleBuilder.createInstancesOfDependencies (node_modules/@nestjs/testing/testing-module.builder.js:118:9)
      at async TestingModuleBuilder.compile (node_modules/@nestjs/testing/testing-module.builder.js:74:9)
      at async Object.<anonymous> (test/integration/files.service.integration.spec.ts:23:35)

  ● Integration tests for FilesResolver › when MODE is local › listDirectory › should list files

    Invalid MODE: unknown

      13 |
      14 |     if (service == undefined) {
    > 15 |       throw new Error(`Invalid MODE: ${mode}`);
         |             ^
      16 |     }
      17 |     return service;
      18 |   }

      at Function.create (src/files/files-service.factory.ts:15:13)
      at InstanceWrapper.useFactory [as metatype] (test/integration/files.service.integration.spec.ts:34:40)
      at TestingInjector.instantiateClass (node_modules/@nestjs/core/injector/injector.js:368:55)
      at callback (node_modules/@nestjs/core/injector/injector.js:65:45)
      at async TestingInjector.resolveConstructorParams (node_modules/@nestjs/core/injector/injector.js:144:24)
      at async TestingInjector.loadInstance (node_modules/@nestjs/core/injector/injector.js:70:13)
      at async TestingInjector.loadProvider (node_modules/@nestjs/core/injector/injector.js:97:9)
      at async /workspaces/DTaaS/servers/lib/node_modules/@nestjs/core/injector/instance-loader.js:56:13
          at async Promise.all (index 4)
      at async TestingInstanceLoader.createInstancesOfProviders (node_modules/@nestjs/core/injector/instance-loader.js:55:9)
      at async /workspaces/DTaaS/servers/lib/node_modules/@nestjs/core/injector/instance-loader.js:40:13
          at async Promise.all (index 1)
      at async TestingInstanceLoader.createInstances (node_modules/@nestjs/core/injector/instance-loader.js:39:9)
      at async TestingInstanceLoader.createInstancesOfDependencies (node_modules/@nestjs/core/injector/instance-loader.js:22:13)
      at async TestingInstanceLoader.createInstancesOfDependencies (node_modules/@nestjs/testing/testing-instance-loader.js:9:9)
      at async TestingModuleBuilder.createInstancesOfDependencies (node_modules/@nestjs/testing/testing-module.builder.js:118:9)
      at async TestingModuleBuilder.compile (node_modules/@nestjs/testing/testing-module.builder.js:74:9)
      at async Object.<anonymous> (test/integration/files.service.integration.spec.ts:23:35)

  ● Integration tests for FilesResolver › when MODE is local › readFile › should read file

    Invalid MODE: unknown

      13 |
      14 |     if (service == undefined) {
    > 15 |       throw new Error(`Invalid MODE: ${mode}`);
         |             ^
      16 |     }
      17 |     return service;
      18 |   }

      at Function.create (src/files/files-service.factory.ts:15:13)
      at InstanceWrapper.useFactory [as metatype] (test/integration/files.service.integration.spec.ts:34:40)
      at TestingInjector.instantiateClass (node_modules/@nestjs/core/injector/injector.js:368:55)
      at callback (node_modules/@nestjs/core/injector/injector.js:65:45)
      at async TestingInjector.resolveConstructorParams (node_modules/@nestjs/core/injector/injector.js:144:24)
      at async TestingInjector.loadInstance (node_modules/@nestjs/core/injector/injector.js:70:13)
      at async TestingInjector.loadProvider (node_modules/@nestjs/core/injector/injector.js:97:9)
      at async /workspaces/DTaaS/servers/lib/node_modules/@nestjs/core/injector/instance-loader.js:56:13
          at async Promise.all (index 4)
      at async TestingInstanceLoader.createInstancesOfProviders (node_modules/@nestjs/core/injector/instance-loader.js:55:9)
      at async /workspaces/DTaaS/servers/lib/node_modules/@nestjs/core/injector/instance-loader.js:40:13
          at async Promise.all (index 1)
      at async TestingInstanceLoader.createInstances (node_modules/@nestjs/core/injector/instance-loader.js:39:9)
      at async TestingInstanceLoader.createInstancesOfDependencies (node_modules/@nestjs/core/injector/instance-loader.js:22:13)
      at async TestingInstanceLoader.createInstancesOfDependencies (node_modules/@nestjs/testing/testing-instance-loader.js:9:9)
      at async TestingModuleBuilder.createInstancesOfDependencies (node_modules/@nestjs/testing/testing-module.builder.js:118:9)
      at async TestingModuleBuilder.compile (node_modules/@nestjs/testing/testing-module.builder.js:74:9)
      at async Object.<anonymous> (test/integration/files.service.integration.spec.ts:23:35)

--------------------|---------|----------|---------|---------|-------------------
File                | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
--------------------|---------|----------|---------|---------|-------------------
All files           |      55 |       50 |   23.33 |   49.49 |                   
 src                |   87.75 |      100 |       0 |   83.78 |                   
  types.ts          |   87.75 |      100 |       0 |   83.78 | 14,20,35,41,67,81 
 src/cloudcmd       |       0 |        0 |       0 |       0 |                   
  cloudcmd.ts       |       0 |        0 |       0 |       0 | 6-31              
 src/enums          |     100 |      100 |     100 |     100 |                   
  ...g-mode.enum.ts |     100 |      100 |     100 |     100 |                   
 src/files          |   52.38 |      100 |      25 |   47.05 |                   
  ...ice.factory.ts |    87.5 |      100 |     100 |   83.33 | 17                
  files.module.ts   |       0 |      100 |       0 |       0 | 22-29             
  files.resolver.ts |   44.44 |      100 |       0 |    37.5 | 12-15,17-20,22    
 src/files/git      |   42.85 |      100 |      50 |      40 |                   
  ...iles.module.ts |       0 |      100 |     100 |       0 | 8                 
  ...les.service.ts |      60 |      100 |      50 |      50 | 15-18             
 ...iles/interfaces |     100 |      100 |     100 |     100 |                   
  ...e.interface.ts |     100 |      100 |     100 |     100 |                   
 src/files/local    |   19.23 |        0 |   22.22 |   16.66 |                   
  ...iles.module.ts |       0 |      100 |     100 |       0 | 8                 
  ...les.service.ts |   20.83 |        0 |   22.22 |   17.39 | 22-67             
--------------------|---------|----------|---------|---------|-------------------
Jest: "global" coverage threshold for lines (50%) not met: 49.49%
Jest: "global" coverage threshold for functions (30%) not met: 23.33%
Test Suites: 1 failed, 1 total
Tests:       3 failed, 3 total
Snapshots:   0 total
Time:        10.257 s
Ran all test suites matching /..\/test\/integration/i.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by prasadtalasila** [comment]
@atomicgamedeveloper The same errors also come on devContainer brought up op top of Ubuntu 24.04.

**Comment by atomicgamedeveloper** [comment]
@prasadtalasila Looking at the code that throws the error, `servers/lib/src/files/files-service.factory.ts`,
```
import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { IFilesService } from './interfaces/files.service.interface.js';

@Injectable()
export default class FilesServiceFactory {
  static create(
    configService: ConfigService,
    fileServices: IFilesService[],
  ): IFilesService {
    const mode = configService.get<string>('MODE');
    const service = fileServices.find((s) => s.getMode() == mode);

    if (service == undefined) {
      throw new Error(`Invalid MODE: ${mode}`);
    }
    return service;
  }
}

}
```
it seems that the issue is a missing `.env` file in the root directory. I am also able to recreate the issue by deleting `/workspaces/DTaaS/servers/lib/.env`.

**Comment by prasadtalasila** [comment]
@atomicgamedeveloper you are right. I forgot about this. I will check it again with `.env` file. Thanks for catching the problem.

**Pull request merged**
