### PR TITLE
Updates npm packages of lib microservice

### PR DESCRIPTION
**Pull request by OliverGeneser**

### CODE REVIEW

**Comment by prasadtalasila** [comment]
@OliverGeneser Thanks for the PR.
Can you please identify the vulnerability that you fixed through this PR? 

Please do check for different versions of transitive dependencies to make sure that they are of same version. The npm seems __might__ have a way to enforce use of same dependency version in all dependencies. Can you check if it helps?

Please do also check the licenses for the all the packages to see if the packages can be used with [GPL Version 3](https://github.com/INTO-CPS-Association/DTaaS/blob/feature/distributed-demo/LICENSE.md) used by DTaaS software. This  [github resource](https://github.com/readme/guides/open-source-licensing) might help.

**Comment by prasadtalasila** [comment]
Please check the commands given in issue #109 to see if the vulnerabilities have been taken care of.

**Comment by OliverGeneser** [comment]
@prasadtalasila This PR fixed 47 vulnerabilities and most relates to DOS vulnerability in semver and word-wrap and Resource Consumption vulnerability in graphql
[audit-output.txt](https://github.com/INTO-CPS-Association/DTaaS/files/12718739/audit-output.txt)

**Review by prasadtalasila — COMMENTED** [review]
Please check the comments posted on issue #109 as well. Thanks.

**Comment by prasadtalasila** [comment]
@OliverGeneser , please rebase your code to the latest commit on the `feature/distributed-demo` branch.

I see two changes in the packages.

1. Addition of `graphql-scalars`. Can you please clarify the reason for adding this?
2. Replacement of `apollo-server-express` with `@apollo/server`. Why is it done?

**Comment by OliverGeneser** [comment]
@prasadtalasila 
Graphql-scalars is added because it is a peer dependency for type-graphql 
Apollo-server-express is replaced with @apollo/server because it is deprecated

**Comment by prasadtalasila** [comment]
@OliverGeneser, using any version is vague. Please change the `grapgql-scalars` to the latest compatible version.

**Pull request merged**
